### ISSUE TITLE
Missing TMX editor

### ISSUE THREAD

**Issue by rmraya** [idimitriadis0/TranslateOnLinux#1]
TMXEditor, [https://www.maxprograms.com/products/tmxeditor.html](https://www.maxprograms.com/products/tmxeditor.html) is not included in the list. It runs on Linux and is able to handle very large TMX files with millions of segments.

**Comment by idimitriadis0** [comment]
Added TMXEditor to the list of TMX editing software for GNU/Linux.

Thank you for the heads up!
