### ISSUE TITLE
All tools open-source

### ISSUE THREAD

**Issue by rmraya** [idimitriadis0/TranslateOnLinux#10]
Hello Jean,

Some updates:

 - All tools published at maxprograms.com are fully open source and free
 - Current Swordfish version is "Swordfish IV" (Swordfish III is too old and unsupported)
 - Anchovy is no longer included in Swordfish installers
 - All tools are free to use 
 - Subscriptions for support and installers are available for Swordfish IV, Stingray, TMXEditor and Fluenta (subscriptions are a conveniency, they are not required to use the tools)

**Comment by idimitriadis0** [comment]
Hello Rodolfo,

I had somehow missed your update. Many thanks for your communication and for your dedication to Libre/Open Source software.

I will soon make an update.

**Comment by idimitriadis0** [comment]
Hello Rodolfo,

The content has been updated to reflect the changes you mention in today's TranslateOnLinux update.

Thanks again!

Jean
