### ISSUE TITLE
Missing term extractor

### ISSUE THREAD

**Issue by rmraya** [idimitriadis0/TranslateOnLinux#2]
Anchovy, [https://www.maxprograms.com/products/anchovy.html](https://www.maxprograms.com/products/anchovy.html) is not listed as a term extractor. It can extract terms from monolingual documents and also from bilingual TMX files.

**Comment by idimitriadis0** [comment]
Mentioned Anchovy under Term extraction > Bilingual term action options for GNU/Linux.

Thank you for the heads up!
