### ISSUE TITLE
SRXEditor installers

### ISSUE THREAD

**Issue by rmraya** [idimitriadis0/TranslateOnLinux#4]
Hi,

SRXEditor is now open source. Code is hosted on GitHub at https://github.com/rmraya/SRXEditor 

Installers are available from its home page, https://www.maxprograms.com/products/srxeditor.html 

SRXEditor is not shipped with Stingray anymore and soon it will not be shipped with Swordfish.

Regards,
Rodolfo M. Raya

**Comment by idimitriadis0** [comment]
Hi Rodolfo,

Thank you for sharing this information and for open sourcing the SRXEditor and offering it as a standalone program.

I have updated the wiki accordingly.

Regards,

Jean Dimitriadis
