### ISSUE TITLE
XLIFF Manager & others

### ISSUE THREAD

**Issue by rmraya** [idimitriadis0/TranslateOnLinux#5]
Hi,

XLIFFChecker does not exist anymore, it is now an integral part of [XLIFF Manager](https://www.maxprograms.com/products/xliffmanager.html).

XLIFF Manager is an open source UI for [OpenXLIFF Filters](https://www.maxprograms.com/products/openxliff.html), an open source set of filters for creating, merging and validating XLIFF 1.2 and 2.0 files.

XLIFF Manager can also generate word count statistics from XLIFF file, including a graphical display of states and matches quality.
Regards,
Rodolfo

**Comment by idimitriadis0** [comment]
Hi Rodolfo,

Many thanks for bringing this to my attention.

XLIFF Manager and OpenXLIFF filters are now mentionned in the Wiki. I will be sure to test XLIFF Manager next time I receive a supported file type that is not natively handled by my current CAT tool.

Regards,
Jean
