### ISSUE TITLE
Yahoo Group moved

### ISSUE THREAD

**Issue by rmraya** [idimitriadis0/TranslateOnLinux#6]
Hi,

The Swordfish Support at [Yahoo](https://groups.yahoo.com/neo/groups/swordfish_support/info) was moved to [Groups.io](https://groups.io/g/maxprograms/)

The group is now intended for supporting all tools published at Maxprograms, not only Swordfish.

**Comment by idimitriadis0** [comment]
Hi,

Thank you for this info, I have updated the wiki, the new link should show up in a few minutes.
