### ISSUE TITLE
Stingray is open source

### ISSUE THREAD

**Issue by rmraya** [idimitriadis0/TranslateOnLinux#8]
Hi,

Stingray aligner, https://www.maxprograms.com/products/stingray.html, is now open source.

Regards,
Rodolfo

**Comment by idimitriadis0** [comment]
Hi Rodolfo,

Thank you for sharing this information and for open sourcing Singray.

I plan to make some batch updates on the website in the coming days, so the relevant section will be updated to reflect this change.

Leaving the ticket open until then.

Regards,
Jean

**Comment by idimitriadis0** [comment]
Wiki updated accordingly, thank you!
